version: '3.1'
services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - 8888:80
      - 4444:443
    volumes:
      - ./code:/var/www/html
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      #- /etc/localtime:/etc/localtime:ro
    environment:
      - "TZ=${TIMEZONE}"
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - 33069:3306
    volumes:
      - ./user-data/mysql:/var/lib/mysql
      #- /etc/localtime:/etc/localtime:ro
    environment:
      - "TZ=${TIMEZONE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: ./build/php/Dockerfile
    container_name: php
    restart: always
    ports:
      - 9000:9000
    volumes:
      - ./code:/var/www/html
    environment:
      - "TZ=${TIMEZONE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_PORT=${MYSQL_PORT}"
      - "MYSQL_HOST=${MYSQL_HOST}"
      - "AUTOCONFIGURE=${AUTOCONFIGURE}"
    networks:
      - laravel

networks:
  laravel: