version: '3.3'
services:

  certbot:
    container_name: certbot
    image: cnsoluciones/certbot:latest
    network_mode: host
    volumes:
      - ./user-data/etc/letsencrypt:/etc/letsencrypt
    environment:
      - domains=${DOMAINS}
      - email=${EMAIL}
